Repository xCDAT/xcdat, pull requests merged in 2021-10, with the labels that each got.

#113 Update `open_dataset()` and `open_mfdataset()` to only run `decode_time_units()` with datasets that have a time dimension
  xcdat/dataset.py
Labels: Type: Bug

#95 Add geospatial averaging
  conda-recipe/meta.yaml
  docs/api.rst
  setup.py
  tests/fixtures.py
  tests/test_dataset.py
  tests/test_spatial_avg.py
  tests/test_xcdat.py
  xcdat/__init__.py
  xcdat/bounds.py
  xcdat/spatial_avg.py
  xcdat/xcdat.py
Labels: Type: Enhancement, Priority: High

#132 Add support for spatial averaging parallelism via Dask
  tests/test_spatial_avg.py
  xcdat/spatial_avg.py
Labels: Type: Bug, Priority: Medium
