Repository xCDAT/xcdat, pull requests merged in 2022-06, with the labels that each got.

#246 Fix parsing of custom seasons for departures
  xcdat/bounds.py
  xcdat/temporal.py
Labels: Type: Bug, Priority: Critical

#247 Enable blank GH issues
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Type: Documentation, Priority: Low

#254 Remove `center_times` kwarg from temporal averaging methods
  docs/api.rst
  tests/test_axis.py
  tests/test_temporal.py
  xcdat/axis.py
  xcdat/dataset.py
  xcdat/temporal.py
Labels: Priority: High, breaking change, Type: Refactor

#239 [DOC] Add CDAT API mapping table and gallery examples
  CONTRIBUTING.rst
  README.rst
  conda-env/dev.yml
  conda-env/readthedocs.yml
  docs/api.rst
  docs/conf.py
  docs/examples/climatology-and-departures.ipynb
  docs/examples/general-utilities.ipynb
  docs/examples/spatial-average.ipynb
  docs/examples/temporal-average-yearly.gif
  docs/examples/temporal-average.ipynb
  docs/gallery.rst
  docs/getting-started.rst
  docs/index.rst
  docs/project-maintenance.rst
  setup.py
  xcdat/__init__.py
Labels: Type: Documentation

#257 Update `swap_lon_axis` to ignore same systems
  tests/test_axis.py
  xcdat/axis.py
Labels: Type: Bug, Priority: High

#252 Update `_get_weights()` method for `SpatialAccessor` and `TemporalAccessor`
  tests/test_spatial.py
  tests/test_temporal.py
  xcdat/axis.py
  xcdat/spatial.py
  xcdat/temporal.py
Labels: Type: Enhancement, Priority: High

#164 Adds horizontal regridding
  conda-env/ci.yml
  conda-env/dev.yml
  docs/api.rst
  setup.py
  tests/test_regrid.py
  xcdat/__init__.py
  xcdat/axis.py
  xcdat/bounds.py
  xcdat/regridder/__init__.py
  xcdat/regridder/accessor.py
  xcdat/regridder/base.py
  xcdat/regridder/grid.py
  xcdat/regridder/regrid2.py
  xcdat/regridder/xesmf.py
Labels: Type: Enhancement, Priority: Critical

#262 Update `get_axis_coord()` to interpret more keys
  README.rst
  conda-env/readthedocs.yml
  docs/api.rst
  docs/examples/general-utilities.ipynb
  docs/index.rst
  tests/fixtures.py
  tests/test_axis.py
  tests/test_bounds.py
  tests/test_dataset.py
  tests/test_regrid.py
  tests/test_spatial.py
  tests/test_temporal.py
  xcdat/__init__.py
  xcdat/axis.py
  xcdat/bounds.py
  xcdat/dataset.py
  xcdat/regridder/accessor.py
  xcdat/regridder/base.py
  xcdat/regridder/grid.py
  xcdat/regridder/regrid2.py
  xcdat/spatial.py
  xcdat/temporal.py
Labels: Type: Enhancement, Priority: High

#263 better handling of non-cf-compliant time data
  tests/fixtures.py
  tests/test_dataset.py
  xcdat/dataset.py
Labels: Type: Bug, Type: Enhancement, Priority: High

#267 Bump to 0.3.0
  .pre-commit-config.yaml
  AUTHORS.rst
  CONTRIBUTING.rst
  HISTORY.rst
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
  setup.py
  tbump.toml
  xcdat/__init__.py
  xcdat/spatial.py
Labels: Type: Release
