Repository xCDAT/xcdat, pull requests merged in 2022-10, with the labels that each got.

#358 Bump to 0.3.3
  HISTORY.rst
  docs/index.rst
  setup.py
  tbump.toml
  xcdat/__init__.py
Labels: Priority: High, Type: Release

#362 Update documentation
  HISTORY.rst
  README.rst
  conda-env/readthedocs.yml
  docs/faqs.rst
  docs/getting-started.rst
  docs/index.rst
Labels: Type: Documentation, Priority: Medium

#365 Update documentation
  README.rst
  docs/examples/climatology-and-departures.ipynb
  docs/faqs.rst
  docs/getting-started.rst
  docs/index.rst
Labels: Type: Documentation

#367 Link repo to Zenodo and upload GitHub releases
  README.rst
Labels: Type: Documentation, Priority: Medium

#368 Automate release notes generation
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Type: DevOps, patch

#370 Update release-drafter template
  .github/release-drafter.yml
Labels: Type: DevOps

#374 Fixes xesmf flag
  tests/test_regrid.py
  xcdat/regridder/xesmf.py
Labels: Type: Bug, Priority: High
