Repository xCDAT/xcdat, pull requests merged in 2022-01, with the labels that each got.

#161 Update xcdat.open_mfdataset time decoding logic
  docs/api.rst
  tests/fixtures.py
  tests/test_dataset.py
  xcdat/__init__.py
  xcdat/dataset.py
Labels: Type: Enhancement

#181 Add FAQs page to docs
  docs/faqs.rst
  docs/index.rst
Labels: Type: Documentation, Priority: Medium

#182 Fix syntax of code examples from PR #181
  docs/faqs.rst
Labels: Type: Documentation, Priority: Low

#186 Replace markdown issue templates with GitHub yml forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Type: Documentation, Priority: Low

#187 Drop support for Python 3.7
  .github/workflows/build_workflow.yml
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
  setup.cfg
  setup.py
  xcdat/axis.py
  xcdat/bounds.py
  xcdat/dataset.py
  xcdat/spatial_avg.py
  xcdat/xcdat.py
Labels: Type: DevOps, Priority: High

#189 Update conda env dependencies
  .pre-commit-config.yaml
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
  setup.py
Labels: Type: DevOps, Priority: Medium

#191 Add deps to `pre-commit` `mypy` and fix issues
  .pre-commit-config.yaml
  xcdat/bounds.py
  xcdat/spatial_avg.py
Labels: Type: Enhancement, Type: DevOps, Priority: High

#193 Update and remove logger debug messages
  tests/test_dataset.py
  tests/test_spatial_avg.py
  xcdat/dataset.py
  xcdat/spatial_avg.py
Labels: Type: DevOps, Priority: Medium

#145 Add function to swap dataset longitude axis orientation
  README.rst
  docs/api.rst
  docs/index.rst
  tests/test_axis.py
  tests/test_dataset.py
  tests/test_spatial_avg.py
  xcdat/__init__.py
  xcdat/axis.py
  xcdat/dataset.py
  xcdat/spatial_avg.py
Labels: Type: Enhancement, Priority: Medium

#196 Remove data variable inference API
  docs/api.rst
  tests/test_dataset.py
  tests/test_spatial_avg.py
  xcdat/__init__.py
  xcdat/dataset.py
  xcdat/spatial_avg.py
  xcdat/xcdat.py
Labels: Priority: High
