Repository xCDAT/xcdat, pull requests merged in 2022-07, with the labels that each got.

#281 Bugfix/278 cannot generate bounds
  tests/test_bounds.py
  xcdat/bounds.py
Labels: Type: Bug

#287 Run CI/CD on "push" and "workflow_dispatch"
  .github/workflows/build_workflow.yml
Labels: Type: DevOps, Type: Documentation, Priority: Medium

#288 Run CI/CD on "push" and "workflow_dispatch"
  .github/workflows/build_workflow.yml
Labels: Priority: High

#280 Pin `numba=0.55.2` in dev env and constrain `numba>=0.55.2` in ci env
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
Labels: Type: Bug, Type: DevOps, Priority: High
