Repository xCDAT/xcdat, pull requests merged in 2022-09, with the labels that each got.

#331 Update README and add HPC/Jupyter Guidance
  .vscode/xcdat.code-workspace
  README.rst
  docs/_static/jupyter-launcher-example.png
  docs/getting-started-hpc-jupyter.rst
  docs/getting-started.rst
  docs/index.rst
Labels: Type: Documentation, Priority: Medium

#340 Fix spatial bugs: handle datasets with domain bounds out of order and zonal averaging
  tests/test_spatial.py
  xcdat/spatial.py
Labels: Type: Bug, Priority: Medium

#344 modify preserve bounds logic
  tests/test_regrid.py
  xcdat/regridder/base.py
Labels: Type: Enhancement

#350 Drop leap days based on CF calendar type to calculate daily climatologies and departures
  docs/examples/climatology-and-departures.ipynb
  tests/test_temporal.py
  xcdat/temporal.py
Labels: Type: Bug, Type: Enhancement, Type: Documentation, Priority: High

#328 Add horizontal regridding gallery notebook
  docs/api.rst
  docs/examples/horizontal-regridding.ipynb
  docs/gallery.rst
  xcdat/regridder/grid.py
Labels: Type: Documentation, Priority: Medium

#355 Add doc for staying up to date with releases
  README.rst
  docs/_static/github-watch-releases-1.png
  docs/_static/github-watch-releases-2.png
  docs/index.rst
Labels: Type: Documentation, Priority: Medium
