Repository xCDAT/xcdat, pull requests merged in 2022-08, with the labels that each got.

#294 update conda install to conda create
  docs/getting-started.rst
Labels: Type: Documentation, Priority: Medium

#283 Bugfix/282 out of bounds datetime
  .pre-commit-config.yaml
  conda-env/dev.yml
  tests/test_dataset.py
  xcdat/dataset.py
Labels: Type: Bug, Priority: High

#298 Update project overview and planned features list
  README.rst
  docs/getting-started.rst
  docs/index.rst
Labels: Type: Documentation, Priority: Medium

#276 Filters safe warnings.
  tests/test_regrid.py
Labels: Priority: Medium

#299 Fix bullet formatting in `README.rst` and`index.rst`
  README.rst
  docs/index.rst
Labels: Type: Documentation, Priority: Medium

#307 Update conda env yml files and add missing dependencies
  .pre-commit-config.yaml
  .vscode/xcdat.code-workspace
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
Labels: Priority: Critical

#302 Use cftime for temporal averaging operations
  tests/fixtures.py
  tests/test_dataset.py
  tests/test_temporal.py
  xcdat/dataset.py
  xcdat/temporal.py
Labels: Type: Bug, Priority: Critical

#309 Fix `open_mfdataset()` dropping time encoding attrs
  tests/test_dataset.py
  xcdat/dataset.py
Labels: Type: Bug, Priority: Critical

#312 Replace "time" references with `self._dim` in `class TemporalAccessor`
  xcdat/temporal.py
Labels: Type: Bug, Priority: Critical

#313 Modify logic to not throw error for singleton coordinates (with no bounds)
  tests/test_bounds.py
  xcdat/bounds.py
Labels: Type: Bug, Priority: High

#318 Fix Jupyter headings not rendering with pandoc
  docs/examples/climatology-and-departures.ipynb
  docs/examples/general-utilities.ipynb
  docs/examples/spatial-average.ipynb
  docs/examples/temporal-average.ipynb
Labels: Type: Documentation, Priority: Medium

#321 Bump to 0.3.1
  .pre-commit-config.yaml
  HISTORY.rst
  README.rst
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
  docs/index.rst
  setup.py
  tbump.toml
  xcdat/__init__.py
  xcdat/axis.py
  xcdat/dataset.py
  xcdat/spatial.py
  xcdat/temporal.py
Labels: Type: Release

#329 Fix multiple temporal avg calls on same dataset breaking
  tests/test_temporal.py
  xcdat/temporal.py
Labels: Type: Bug, Priority: Critical

#320 fix incorrect results for group averaging with missing data
  tests/test_temporal.py
  xcdat/temporal.py
Labels: Type: Bug, Priority: High
