Repository xCDAT/xcdat, pull requests merged in 2023-03, with the labels that each got.

#422 Add presentations and demos to sphinx toctree
  docs/conf.py
  docs/demos.rst
  docs/demos/1-25-23-cwss-seminar/introduction-to-xcdat.ipynb
  docs/examples/introduction-to-xcdat.ipynb
  docs/index.rst
Labels: Type: Documentation, Priority: Medium

#385 Wrap open_dataset and open_mfdataset to flexibly open datasets
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
  tests/test_dataset.py
  xcdat/dataset.py
Labels: Type: Enhancement

#417 Update departures and climatology APIs with reference period
  docs/examples/climatology-and-departures.ipynb
  tests/test_temporal.py
  xcdat/temporal.py
Labels: Type: Enhancement

#428 [Doc]: Fix missing `xesmf` APIs and update slides in intro notebook
  docs/conf.py
  docs/examples/introduction-to-xcdat.ipynb
Labels: Type: Bug, Type: Documentation

#432 Updates xesmf docs
  docs/examples/horizontal-regridding.ipynb
  xcdat/regridder/accessor.py
  xcdat/regridder/xesmf.py
Labels: Type: Documentation

#425 Update xsearch-xcdat-example.ipynb
  docs/demos/1-25-23-cwss-seminar/xsearch-xcdat-example.ipynb
Labels: Type: Documentation

#443 Replace LLNL E3SM License with xCDAT License
  CODE-OF-CONDUCT.rst
  CONTRIBUTING.rst
  LICENSE
  NOTICE
  README.rst
  docs/code-of-conduct.rst
  docs/conf.py
  docs/faqs.rst
  docs/index.rst
Labels: Type: Documentation

#444 Fix README link to CODE-OF-CONDUCT.rst
  README.rst
  conda-env/dev.yml
  conda-env/readthedocs.yml
  docs/index.rst
Labels: Type: Bug, Type: Documentation
