Repository xCDAT/xcdat, pull requests merged in 2023-11, with the labels that each got.

#566 Make xESMF a required dependency
  conda-env/ci.yml
  conda-env/dev.yml
  docs/getting-started.rst
  tests/__init__.py
  tests/test_regrid.py
  xcdat/regridder/__init__.py
  xcdat/regridder/accessor.py
  xcdat/regridder/xesmf.py
Labels: Type: DevOps, Type: Documentation

#571 Update doc: Add link to the video
  docs/demos.rst
Labels: Type: Documentation, minor

#572 Bump to 0.6.1
  .github/workflows/build_workflow.yml
  HISTORY.rst
  setup.py
  tbump.toml
  xcdat/__init__.py
  xcdat/bounds.py
Labels: Type: Documentation, Type: Release, minor
