Repository xCDAT/xcdat, pull requests merged in 2023-06, with the labels that each got.

#503 Deprecate CDML/XML support in `open_mfdataset()`
  tests/test_dataset.py
  xcdat/dataset.py
Labels: Type: Documentation

#504 Remove cdms-filemap references in API docstrings
  xcdat/dataset.py
Labels: Type: Documentation

#495 Fix multi-file dataset spatial average orientation and weights when lon bounds span prime meridian
  tests/test_spatial.py
  xcdat/spatial.py
Labels: Type: Bug

#481 Improves error when axis is missing/incorrect attributes
  tests/test_regrid.py
  xcdat/regridder/regrid2.py
Labels: Type: Bug

#388 Add API extending xgcm vertical regridding
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
  docs/api.rst
  docs/examples/regridding-horizontal.ipynb
  docs/examples/regridding-vertical.ipynb
  docs/gallery.rst
  tests/fixtures.py
  tests/test_axis.py
  tests/test_regrid.py
  xcdat/axis.py
  xcdat/regridder/__init__.py
  xcdat/regridder/accessor.py
  xcdat/regridder/base.py
  xcdat/regridder/grid.py
  xcdat/regridder/regrid2.py
  xcdat/regridder/xesmf.py
  xcdat/regridder/xgcm.py
Labels: Type: Enhancement

#509 Update documentation in regrid2.py
  xcdat/regridder/regrid2.py
Labels: Type: Documentation, minor

#512 Simplify conda environments and move configs to `pyproject.toml`
  .github/workflows/build_workflow.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
  pyproject.toml
  setup.cfg
Labels: Type: DevOps, Type: Documentation

#514 Fix Python deprecation comment in conda env yml files
  conda-env/ci.yml
  conda-env/dev.yml
Labels: Type: Bug, Type: DevOps
