Repository xCDAT/xcdat, pull requests merged in 2023-10, with the labels that each got.

#535 General update to regridding
  docs/api.rst
  docs/examples/regridding-horizontal.ipynb
  docs/examples/regridding-vertical.ipynb
  docs/faqs.rst
  tests/fixtures.py
  tests/test_regrid.py
  xcdat/regridder/accessor.py
  xcdat/regridder/regrid2.py
  xcdat/regridder/xesmf.py
  xcdat/regridder/xgcm.py
Labels: Type: Bug, Type: Feature, Type: Documentation, minor

#555 Bump to v0.6.0
  .vscode/xcdat.code-workspace
  HISTORY.rst
  docs/faqs.rst
  setup.py
  tbump.toml
  xcdat/__init__.py
Labels: Type: Documentation, minor

#559 Fix v0.6.0 changelog headers for proper nesting
  HISTORY.rst
Labels: Type: Bug, Type: Documentation
