Repository xCDAT/xcdat, pull requests merged in 2023-05, with the labels that each got.

#465 Update DevOps to cache conda and fix attributes not being preserved with `xarray > 2023.3.0`
  .github/workflows/build_workflow.yml
  conda-env/ci.yml
  conda-env/dev.yml
  conda-env/readthedocs.yml
  tests/test_bounds.py
  tests/test_dataset.py
  tests/test_regrid.py
  tests/test_temporal.py
  xcdat/_logger.py
  xcdat/bounds.py
  xcdat/dataset.py
  xcdat/regridder/base.py
  xcdat/temporal.py
Labels: Type: Bug, Type: DevOps

#474 Update FAQs question covering datasets with conflicting bounds
  .github/workflows/build_workflow.yml
  docs/faqs.rst
Labels: Type: Documentation

#479 Add Q&A GH discussions template
  .github/DISCUSSION_TEMPLATE/q-a.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: Type: Documentation

#480 Add more fields to GH Discussions question form
  .github/DISCUSSION_TEMPLATE/2-questions.yml
Labels: Type: Documentation

#468 Fixes preserving ds/da attributes in the regrid2 module
  tests/test_regrid.py
  xcdat/regridder/regrid2.py
Labels: Type: Bug, Priority: High

#491 Typo fix for doc
  xcdat/temporal.py
Labels: Type: Bug
