Repository xCDAT/xcdat, pull requests merged in 2024-09, with the labels that each got.

#689 [Refactor] Improve the performance of temporal group averaging
  .vscode/xcdat.code-workspace
  tests/test_temporal.py
  xcdat/temporal.py
Labels: type: enhancement

#691 Update `setup.py` classifiers
  setup.py
Labels: type: docs

#696 Update temporal.py to properly handle piControl simulations
  xcdat/temporal.py
Labels: type: bug

#698 Update build workflow
  .github/workflows/build_workflow.yml
Labels: type: devops
