Repository xCDAT/xcdat, pull requests merged in 2024-03, with the labels that each got.

#533 [PR]: Improving regrid2 performance
  tests/test_regrid.py
  xcdat/regridder/regrid2.py
Labels: type: enhancement, priority: now

#617 Add list of projects using xCDAT
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/enhancement_request.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  README.rst
Labels: type: docs, Type: Documentation

#623 Fix climo notebook missing T bounds and add notebook env setup in all example notebooks
  docs/examples/climatology-and-departures.ipynb
  docs/examples/general-utilities.ipynb
  docs/examples/introduction-to-xcdat.ipynb
  docs/examples/regridding-horizontal.ipynb
  docs/examples/regridding-vertical.ipynb
  docs/examples/spatial-average.ipynb
  docs/examples/temporal-average.ipynb
Labels: type: bug
