Repository xCDAT/xcdat, pull requests merged in 2025-05, with the labels that each got.

#721 Drop Python 3.9 support and add compatibility for Python 3.13
  .github/workflows/build_workflow.yml
  conda-env/ci.yml
  conda-env/dev.yml
  docs/conf.py
  pyproject.toml
  tests/test_regrid.py
  xcdat/axis.py
  xcdat/bounds.py
  xcdat/dataset.py
  xcdat/regridder/accessor.py
  xcdat/regridder/base.py
  xcdat/regridder/grid.py
  xcdat/regridder/regrid2.py
  xcdat/regridder/xesmf.py
  xcdat/regridder/xgcm.py
  xcdat/spatial.py
  xcdat/temporal.py
  xcdat/tutorial.py
  xcdat/utils.py
Labels: type: devops, type: docs

#759 Add `.zenodo.json` and `CITATION.cff` to cite core authors
  .zenodo.json
  CITATION.cff
Labels: type: docs

#767 Eliminate performance bottleneck in `temporal.group_average()`
  xcdat/temporal.py
Labels: type: enhancement

#768 Use the median of the delta instead of min for time freq inference
  tests/test_temporal.py
  xcdat/temporal.py
Labels: type: enhancement
